// <auto-generated />
using System;
using DataAccessLayer.ApplicationDbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(BookingDbContext))]
    partial class BookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {

            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

      

            modelBuilder.Entity("DataAccessLayer.Models.Users", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INT")
                        .HasColumnName("UserId")
                        .UseIdentityColumn();

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("CreatedDate");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("email");

                 

                   
                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("DATETIME")
                        .HasColumnName("ModifiedDate");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)")
                        .HasColumnName("password");

                  

                    b.HasKey("UserId")
                        .HasName("pk_Users");

                

                    b.ToTable("Users");
                });
            modelBuilder.Entity("DataAccessLayer.Models.Trips", b =>
            {
                b.Property<int>("TripId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INT")
                    .HasColumnName("TripId")
                    .UseIdentityColumn();

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("DATETIME")
                    .HasColumnName("CreatedDate");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("NVARCHAR(100)")
                    .HasColumnName("Name");

                b.Property<string>("CityName")
                    .HasColumnType("NVARCHAR(100)")
                    .HasColumnName("CityName");


                b.Property<DateTime>("ModifiedDate")
                    .HasColumnType("DATETIME")
                    .HasColumnName("ModifiedDate");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("NVARCHAR(100)")
                    .HasColumnName("password");
                b.Property<string>("ImageUrl")
             .IsRequired()
             .HasColumnType("NVARCHAR(100)")
             .HasColumnName("ImageUrl");


                b.HasKey("TripId")
                    .HasName("pk_Trips");



                b.ToTable("Trips");
            });





        }
    }
}
